### ISSUE TITLE
View for Shipment Order Items

### ISSUE THREAD

**Issue by gurveenbagga** [hotwax/ofbiz-mantle-udm#1]
1. New view to fetch Fulfilled Order Items, for this we should include data model for Shipment Item and related entities.
1. The view could contain items which are packed etc, and based on the Shipment Status, the view will be used to prepare the Fulfilled Order Items Feed, as the status will be 'SHIPMENT_SHIPPED' for such records.
1. This should be created keeping in mind all scenarios of Explode ON/OFF and partial/complete fulfillment.
1. For fulfilled order items, the feeds will be generated Shipment Item wise and not order Item wise.
   1. Eg. for Explode OFF scenario, for an order item with qty=7, brokered partially to 2 facilities so 2 Ship groups and Assoc records.
   1. For above say 2 records with qty 4 and 3 respectively for ship group 1 & 2.
   1. After fulfillment, the feed should be generated shipment item wise.
   1. The Shipment Item can have records like explode ON case i.e. new record for every single qty i.e. overall 7 records.
   1. This can be the due to our API behavior to always consider single qty when fulfilling order item.
   1. This may not always be the case, this is the current behavior.
   1. So even if multiple qties get fulfilled, then qty gets set accordingly in the Shipment Item.
   1. So in every scenario we will consider Shipment Items and prepare the feed and data taking reference from it.

NOTE: IMP
1. We need to consider the **completed order items with products of type digital_good or donation.**
2. Such product types are completed but no shipments are created.
3. So this view will not be able to fetch the records for such completed order items and if any feed is prepared to send the fulfilled order items, then they will be missed.
4. So we should create view from Order Item and related entities and include Shipment and related entities with join-optional as true so that all the shipped/completed items can be fetched using this view.

**Comment by gurveenbagga** [comment]
We need to consider the scenario of completed order items with products of type digital_good or donation .

1. Such product types are completed but no shipments are created.
2. So this view will not be able to fetch the records for such completed order items and if any feed is prepared to send the fulfilled order items, then they will be missed.
3. So we should create view from Order Item and related entities and include Shipment and related entities with join-optional as true so that all the shipped/completed items can be fetched using this view.
4. Added this detail as NOTE in the issue description as well.

@yaminibhagat

**Comment by yaminibhagat** [comment]
1. Improved the ShipmentOrderItemsSyncQueue view.
2. Verified the view for 'DIGITAL_GOOD', 'DONATION', and 'FINISHED_GOOD' and found the new scenario in the case of   DIGITAL_GOOD and DONATION.
3. In the shipment entity, there are no records created for the DIGITAL_GOOD and DONATION. because 'DIGITAL_GOOD' and 'DONATION'  does not ship.
4. Currently for fetching the quantity of a shipped item we are using the Shipment_Item entity.
5. But in the case of DIGITAL_GOOD and DONATION we can't we Shipment_Item entity.
6. Discussed the scenario with Gurveen ma'am.

**TODO**

1. Which field do we use for quantity in the case of 'DIGITAL_GOOD' and 'DONATION'?
2. Need to add the is_Physical field in the view.
 
**Note**: - Need to discuss this scenario with Deepak sir.

**Comment by yaminibhagat** [comment]
30 Jan '23
Discussion with @gurveenbagga 

1. Dissused the FulfilledOrderItemsSyncQueue view refactoring.
2. In the OrderShipment entity only SHIPMENT_SHIPPED type records will be created.
3. In the OrderItemShipGrpInvRes entity records will be created when an order will be approved. 
4. After completion of the Order, records will be deleted from the OrderItemShipGrpInvRes entity.
